HOTEL/Models/RoomTypes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RoomTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomTypes()
        {
            this.Rooms = new HashSet<Rooms>();
        }
        [Display(Name = "Id")]
        public int RoomTypeId { get; set; }
        [Display(Name = "Название")]
        public string RoomTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}

HOTEL/Models/Rooms.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rooms
    {
        [Display(Name = "Id комнаты")]
        public int RoomId { get; set; }
        [Display(Name = "Номер комнаты")]
        public string RoomNumber { get; set; }
        [Display(Name = "Стоимость")]
        public int RoomPrice { get; set; }
        [Display(Name = "Тип комнаты")]
        public int RoomTypeId { get; set; }
        [Display(Name = "Вместимость")]
        public int RoomCapacity { get; set; }
        [Display(Name = "Описание")]
        public string RoomDescription { get; set; }
        [Display(Name = "Фото 1")]
        public byte[] RoomImage1 { get; set; }
        [Display(Name = "Фото 2")]
        public byte[] RoomImage2 { get; set; }
        [Display(Name = "Фото 3")]
        public byte[] RoomImage3 { get; set; }
        [Display(Name = "Фото 4")]
        public byte[] RoomImage4 { get; set; }
        [Display(Name = "Фото 5")]
        public byte[] RoomImage5 { get; set; }
        [Display(Name = "Площадь")]
        public Nullable<int> Square { get; set; }
    
        public virtual RoomTypes RoomTypes { get; set; }
    }
}

HOTEL/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using HOTEL.Models;
using HOTEL.ViewModel;


namespace HOTEL.Controllers
{
    public class RoomsController : Controller
    {
        public HotelDBEntities db = new HotelDBEntities();

        public ActionResult GetImage(int id, int imageNumber)
        {
            var room = db.Rooms.Find(id);

            byte[] imageBytes = null;
            switch (imageNumber)
            {
                case 1:
                    imageBytes = room.RoomImage1;
                    break;
                case 2:
                    imageBytes = room.RoomImage2;
                    break;
                case 3:
                    imageBytes = room.RoomImage3;
                    break;
                case 4:
                    imageBytes = room.RoomImage4;
                    break;
                case 5:
                    imageBytes = room.RoomImage5;
                    break;
            }

            if (imageBytes != null)
            {
                return File(imageBytes, "image/jpeg");
            }
            else
            {
                return null;
            }
        }

        public ActionResult ListRooms()
        {
            var availableRooms = from r in db.Rooms
                                 
                                 group r by r.RoomTypes.RoomTypeName into g
                                 select g.FirstOrDefault();

            return View(availableRooms.ToList());

        }



        // GET: Rooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var room = from r in db.Rooms
                                 where r.RoomId==id
                                 select r;
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room.ToList());
        }



        public ActionResult Index(string Person, string DateFrom = null, string DateTo = null)
        {
            DateTime datefrom = DateTime.Today.AddDays(1);
            DateTime dateto = DateTime.Today.AddDays(3);


            if (!string.IsNullOrEmpty(DateFrom))
                DateTime.TryParseExact(DateFrom, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out datefrom);

            if (!string.IsNullOrEmpty(DateTo))
                DateTime.TryParseExact(DateTo, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out dateto);

            ViewData["DateFrom"] = datefrom.ToString("yyyy-MM-dd");
            ViewData["DateTo"] = dateto.ToString("yyyy-MM-dd");
            ViewData["Person"] = Person;

            if (User.IsInRole("Admin"))
            {
                var allRooms = from r in db.Rooms
                               select r;

                return View(allRooms.ToList());
            }
            else
            {
                int PE = Convert.ToInt32(Person);

                var availableRooms = from r in db.Rooms
                                     where r.RoomCapacity >= PE &&
                                          !db.RoomBookings.Any(b => b.AssignRoomId == r.RoomId &&
                                         ((b.BookingFrom <= datefrom && b.BookingTo > datefrom) ||
                                         (b.BookingFrom < dateto && b.BookingTo >= dateto) ||
                                         (b.BookingFrom >= datefrom && b.BookingTo <= dateto)))
                                     select r;

                return View(availableRooms.ToList());
            }
        }

        // GET: Rooms/Create
        public ActionResult Create()
        {
            RoomViewModel objRoomViewModel = new RoomViewModel();
            objRoomViewModel.ListOfRoomType = (from obj in db.RoomTypes
                                               select new SelectListItem()
                                               {
                                                   Text = obj.RoomTypeName,
                                                   Value = obj.RoomTypeId.ToString()
                                               }).ToList();
            return View(objRoomViewModel);
        }

        // POST: Rooms/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoomId,RoomNumber,RoomPrice,RoomTypeId,RoomCapacity,Square,RoomDescription,RoomImage1,RoomImage2,RoomImage3,RoomImage4,RoomImage5")] Rooms room, HttpPostedFileBase upload0, HttpPostedFileBase upload1, HttpPostedFileBase upload2, HttpPostedFileBase upload3, HttpPostedFileBase upload4)
        {
            if (ModelState.IsValid)
            {
                if (upload0 != null && upload0.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload0.InputStream))
                    {
                        room.RoomImage1 = reader.ReadBytes(upload0.ContentLength);
                    }
                }
                if (upload1 != null && upload1.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload1.InputStream))
                    {
                        room.RoomImage2 = reader.ReadBytes(upload1.ContentLength);
                    }
                }
                if (upload2 != null && upload2.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload2.InputStream))
                    {
                        room.RoomImage3 = reader.ReadBytes(upload2.ContentLength);
                    }
                }
                if (upload3 != null && upload3.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload3.InputStream))
                    {
                        room.RoomImage4 = reader.ReadBytes(upload3.ContentLength);
                    }
                }
                if (upload4 != null && upload4.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload4.InputStream))
                    {
                        room.RoomImage5 = reader.ReadBytes(upload4.ContentLength);
                    }
                }

                db.Rooms.Add(room);

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(room);
        }

        public ActionResult Edit(int? id, int? roomId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var config = new MapperConfiguration(cfg => {
                cfg.CreateMap<Rooms, RoomViewModel>();
            });
            var mapper = config.CreateMapper();

            var room = db.Rooms.Find(id);
            var roomViewModel = mapper.Map<RoomViewModel>(room);

            // Заполнение списка ListOfRoomType
            roomViewModel.ListOfRoomType = db.RoomTypes.Select(x => new SelectListItem
            {
                Value = x.RoomTypeId.ToString(),
                Text = x.RoomTypeName
            }).ToList();

            if (room == null)
            {
                return HttpNotFound();
            }

            return View(roomViewModel);
        }

        // POST: Rooms/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoomId,RoomNumber,RoomPrice,RoomTypeId,RoomCapacity,Square,RoomDescription,RoomImage1,RoomImage2,RoomImage3,RoomImage4,RoomImage5")] Rooms room, HttpPostedFileBase[] uploads)
        {
            if (ModelState.IsValid)
            {
                for (int i = 0; i < uploads.Length; i++)
                {
                    HttpPostedFileBase upload = uploads[i];
                    if (upload != null && upload.ContentLength > 0)
                    {
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            switch (i)
                            {
                                case 0:
                                    room.RoomImage1 = reader.ReadBytes(upload.ContentLength);
                                    break;
                                case 1:
                                    room.RoomImage2 = reader.ReadBytes(upload.ContentLength);
                                    break;
                                case 2:
                                    room.RoomImage3 = reader.ReadBytes(upload.ContentLength);
                                    break;
                                case 3:
                                    room.RoomImage4 = reader.ReadBytes(upload.ContentLength);
                                    break;
                                case 4:
                                    room.RoomImage5 = reader.ReadBytes(upload.ContentLength);
                                    break;
                            }
                        }
                    }
                }

                db.Entry(room).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("Index");

HOTEL/Views/Rooms/Create.cshtml
@model HOTEL.ViewModel.RoomViewModel

@{
    ViewBag.Title = "Номера";
}

<h2>Создание номера</h2>


@using (Html.BeginForm("Create", "Rooms", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Room</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.RoomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RoomPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.RoomTypeId, Model.ListOfRoomType, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RoomTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomCapacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RoomCapacity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Square, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Square, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Square, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.RoomDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RoomDescription, "", new { @class = "text-danger" })
        </div>
    </div>


    @*Загрузка фотографий*@
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage1, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload0" value="Обзор..." />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage2, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload1" value="Обзор..." />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage3, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload2" value="Обзор..." />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage4, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload3" value="Обзор..." />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage5, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload4" value="Обзор..." />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink(" < Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HOTEL/Views/Rooms/Delete.cshtml
@model HOTEL.Models.Rooms

@{
    ViewBag.Title = "Номера";
}

<h3>Вы действительно хотите удалить эту запись?</h3>
<div>
    <h4>Номера</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomCapacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomDescription)
        </dd>

       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("< Назад к списку", "Index")
        </div>
    }
</div>

HOTEL/Views/Rooms/Edit.cshtml
@model HOTEL.ViewModel.RoomViewModel

@{
    ViewBag.Title = "Номера";
}




@using (Html.BeginForm("Edit", "Rooms", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Номера</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.RoomId)

    <div class="form-group">
        @Html.LabelFor(model => model.RoomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RoomPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.RoomTypeId, Model.ListOfRoomType, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RoomTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomCapacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RoomCapacity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Square, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Square, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Square, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RoomDescription, "", new { @class = "text-danger" })
        </div>
    </div>


    @*Загрузка фотографий*@
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage1, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="uploads[0]" value="Обзор..." />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage2, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="uploads[1]" value="Обзор..." />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage3, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="uploads[2]" value="Обзор..." />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage4, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="uploads[3]" value="Обзор..." />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomImage5, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="uploads[4]" value="Обзор..." />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HOTEL/Views/Rooms/ListRooms.cshtml
@model IEnumerable<HOTEL.Models.Rooms>

@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Filippov Hotel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <script src="https://kit.fontawesome.com/bacc822a81.js" crossorigin="anonymous"></script>
    <style>
        section.site-hero {
            padding-top: 100px; /* Высота стандартного верхнего меню Bootstrap */
        }

        .carousel {
            max-width: 600px;
            margin: 0 auto;
        }

        .carousel-inner .item img {
            width: 100%;
            height: 300px;
            object-fit: cover;
        }

        h1.heading {
            color: goldenrod;
            font-family: "Playfair Display", times, serif;
            font-size: 2em;
        }
    </style>
</head>
@using (Html.BeginForm())
{
    <div class="container">
        <br />
        <h1 class="heading">БРОНИРОВАНИЕ</h1>
        <h4>ГАРАНТИЯ ЛУЧШЕЙ ЦЕНЫ</h4>
        <br />
        <p>Почему выгодно бронировать на Filippov HOTEL?</p>
        <p>Когда вы бронируете на официальном сайте Отеля, мы гарантируем, что <b>вы найдете самые низкие цены и получите наилучшие условия.</b> Да, здесь цена ниже, чем на туристических сайтах, и <b>мы предоставим множество других исключительных преимуществ</b>, чтобы максимально улучшить ваше пребывание  у нас.</p>

        <br />
    </div>

    <br />

    <div class="row" style="padding-left:18%; padding-right:18%">
        @foreach (var room in Model)
        {
            <div class="col-md-12" style="margin-top:15px;margin-bottom:15px">
                <div class="room-block card mb-6">
                    <div class="row">
                        <div class="col-md-6">
                            <div id="myCarousel-@room.RoomId" class="carousel slide" data-ride="carousel">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    @for (int i = 0; i < 5; i++)
                                    {
                                        <li data-target="#myCarousel-@room.RoomId" data-slide-to="@i" class="@((i == 0) ? "active" : "")"></li>
                                    }
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner" role="listbox">
                                    <div class="item active">
                                        <img src="@Url.Action("GetImage", "Rooms", new { id = room.RoomId, imageNumber = 1 })" alt="Room Image 1" />
                                    </div>
                                    <div class="item">
                                        <img src="@Url.Action("GetImage", "Rooms", new { id = room.RoomId, imageNumber = 2 })" alt="Room Image 2" />
                                    </div>
                                    <div class="item">
                                        <img src="@Url.Action("GetImage", "Rooms", new { id = room.RoomId, imageNumber = 3 })" alt="Room Image 3" />
                                    </div>
                                    <div class="item">
                                        <img src="@Url.Action("GetImage", "Rooms", new { id = room.RoomId, imageNumber = 4 })" alt="Room Image 4" />
                                    </div>
                                    <div class="item">
                                        <img src="@Url.Action("GetImage", "Rooms", new { id = room.RoomId, imageNumber = 5 })" alt="Room Image 5" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card-body d-flex flex-column">
                                <h3 class="card-title" style="color:goldenrod">@room.RoomTypes.RoomTypeName</h3>
                                <br />
                                <p class="card-text"><i class="fas fa-users-cog mr-1"></i> &nbsp;до @room.RoomCapacity гостей &nbsp;&nbsp;&nbsp;<i class="bi bi-arrows-angle-expand"></i>&nbsp; @room.Square м²</p>
                                <br />
                                <p class="card-text">@room.RoomDescription</p>
                                <br />
                                <button type="button" onclick="location.href='@Url.Action("Details", new { id = room.RoomId })'" class="btn btn-primary">Подробнее</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

}