HOTEL/Models/RoomBookings.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RoomBookings
    {
        [Display(Name = "Номер бронирования")]
        public int BookingId { get; set; }
        [Display(Name = "ФИО")]
        public string CustomerName { get; set; }
        [Display(Name = "Телефон")]
        public string CustomerNumber { get; set; }
        [Display(Name = "Адрес")]
        public string CustomerAdress { get; set; }
        [Display(Name = "Дата заезда")]
        public System.DateTime BookingFrom { get; set; }
        [Display(Name = "Дата выезда")]
        public System.DateTime BookingTo { get; set; }
        [Display(Name = "Номер комнаты")]
        public int AssignRoomId { get; set; }
        [Display(Name = "Ночей")]
        public int NoOfMembers { get; set; }
        [Display(Name = "Итоговая стоимость")]
        public decimal TotalAmount { get; set; }
        [Display(Name = "Тип оплаты")]
        public Nullable<int> PaymentTypeId { get; set; }
        [Display(Name = "Почта")]
        public string CustomerEmail { get; set; }
        [Display(Name = "Доп. услуги")]
        public Nullable<int> ServiceId { get; set; }
        [Display(Name = "Гость 1")]
        public string CustomerName1 { get; set; }
        [Display(Name = "Гость 2")]
        public string CustomerName2 { get; set; }
        [Display(Name = "Гость 3")]
        public string CustomerName3 { get; set; }
        [Display(Name = "Комментарии")]
        public string Comments { get; set; }
        [Display(Name = "Статус")]
        public Nullable<int> Confirmed { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Services Services { get; set; }
    }
}

HOTEL/Controllers/RoomBookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using HOTEL.Models;
using HOTEL.ViewModel;
using MailKit.Security;
using MimeKit;

namespace HOTEL.Controllers
{
    public class RoomBookingsController : Controller
    {
        private HotelDBEntities db = new HotelDBEntities();

        // GET: RoomBookings
        public ActionResult Index(string searchString, string bookingId, string customerNumber)
        {
            var bookings = db.RoomBookings.Include(r => r.PaymentType);

            if (User.IsInRole("Admin"))
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    bookings = bookings.Where(b =>
                        b.CustomerName.Contains(searchString) ||
                        b.CustomerEmail.Contains(searchString) ||
                        b.CustomerNumber.Contains(searchString) ||
                        b.Comments.Contains(searchString) ||
                        b.AssignRoomId.ToString().Contains(searchString));
                }

                if (!string.IsNullOrEmpty(bookingId))
                {
                    int id = int.Parse(bookingId);
                    bookings = bookings.Where(b => b.BookingId == id);
                }

                if (!string.IsNullOrEmpty(customerNumber))
                {
                    bookings = bookings.Where(b => b.CustomerNumber == customerNumber);
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(searchString) || !string.IsNullOrEmpty(bookingId) || !string.IsNullOrEmpty(customerNumber))
                {
                    if (!string.IsNullOrEmpty(searchString))
                    {
                        bookings = bookings.Where(b =>
                            b.CustomerName.Contains(searchString) ||
                            b.CustomerEmail.Contains(searchString) ||
                            b.CustomerNumber.Contains(searchString) ||
                            b.Comments.Contains(searchString) ||
                            b.AssignRoomId.ToString().Contains(searchString));
                    }

                    if (!string.IsNullOrEmpty(bookingId))
                    {
                        int id = int.Parse(bookingId);
                        bookings = bookings.Where(b => b.BookingId == id);
                    }

                    if (!string.IsNullOrEmpty(customerNumber))
                    {
                        bookings = bookings.Where(b => b.CustomerNumber == customerNumber);
                    }
                }
                else
                {
                    bookings = Enumerable.Empty<RoomBookings>().AsQueryable();
                }
            }

            bookings = bookings.OrderByDescending(b => b.BookingId);
            return View(bookings.ToList());
        }

        // GET: RoomBookings/Create
        public ActionResult Create(int roomId, string DateFrom, string DateTo, int? roomPrice, string person)
        {
            DateTime datefrom = DateTime.Today.AddDays(1);
            string dateFromText = datefrom.ToString("d MMMM");
            DateTime dateto = DateTime.Today.AddDays(3);
            string dateToText = dateto.ToString("d MMMM");

            if (DateFrom != null)
                DateTime.TryParseExact(DateFrom, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out datefrom);
                dateFromText = datefrom.ToString("d MMMM");

            if (DateTo != null)
                DateTime.TryParseExact(DateTo, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out dateto);
                dateToText = dateto.ToString("d MMMM");

            
            

            TimeSpan span = dateto - datefrom;
            int days = span.Days;

            int totalPrice = roomPrice.Value * days;

            ViewBag.ID = roomId;

            ViewBag.DF = datefrom;
            ViewBag.DT = dateto;
            ViewBag.DFtxt = dateFromText;
            ViewBag.DTtxt = dateToText;
            ViewBag.PE = person;
            ViewBag.RP = roomPrice;
            ViewBag.days = days;
            ViewBag.totalPrice = totalPrice;
            
            return View();
        }

        // POST: RoomBookings/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingId,CustomerName,CustomerNumber,CustomerEmail,CustomerAdress,CustomerName1,CustomerName2,CustomerName3,BookingFrom,BookingTo,AssignRoomId,NoOfMembers,TotalAmount,PaymentTypeId,ServiceId,Comments,Confirmed")] RoomBookings roomBookings)
        {
            if (ModelState.IsValid)
            {
                
                // создаем новую запись
                db.RoomBookings.Add(roomBookings);
                

                db.SaveChanges();

                // Проверяем наличие адреса электронной почты
                if (!string.IsNullOrEmpty(roomBookings.CustomerEmail))
                {
                    try
                    {
                        // Отправляем письмо
                        MailMessage message = new MailMessage();
                        message.From = new MailAddress("vil_2003@mail.ru");
                        message.To.Add(roomBookings.CustomerEmail);
                        message.Subject = "Данные бронирования";
                        message.Body = $"Уважаемый {roomBookings.CustomerName}," +
                            $"\n\nБлагодарим, за то, что бронируете у нас. Прилагаем ваши детали бронирования:" +
                            $"\n\nНомер бронирования: {roomBookings.BookingId}" +
                            $"\nСтоимость: {roomBookings.TotalAmount}" +
                            $"\nЗаселение: {roomBookings.BookingFrom}" +
                            $"\nВыезд: {roomBookings.BookingTo}" +
                            $"\nНочей: {roomBookings.NoOfMembers}" +
                            $"\n\nМы надеемся ваше прибывание будет комфортным у нас.\n\nС наилучшими пожеланиями,\nАдминистрация отеля";

                        // Задаем SMTP-сервер и его порт
                        SmtpClient smtp = new SmtpClient("smtp.mail.ru", 587);
                        smtp.UseDefaultCredentials = false;
                        smtp.Credentials = new NetworkCredential("vil_2003@mail.ru", "iA7RuDeFW8dBTtiUNqqn");
                        smtp.EnableSsl = true;

                        smtp.Send(message);
                    }
                    catch (Exception ex)
                    {
                        // Обрабатываем ошибки при отправке сообщения
                        ModelState.AddModelError("", "Ошибка при отправке сообщения: " + ex.Message);
                        return View(roomBookings);
                    }
                }

                return RedirectToAction("Index", "Home");
            }

            return View(roomBookings);
        }

        // GET: RoomBookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomBookings roomBookings = db.RoomBookings.Find(id);

            List<SelectListItem> confirmedList = new List<SelectListItem>
    {
        new SelectListItem { Value = "1", Text = "Новое" },
        new SelectListItem { Value = "2", Text = "Подтверждено" },
        new SelectListItem { Value = "3", Text = "В работе" },
        new SelectListItem { Value = "4", Text = "Завершено" },
        new SelectListItem { Value = "5", Text = "Отменено" }
    };

            // Передаем список в ViewBag
            ViewBag.ConfirmedList = confirmedList;

            if (roomBookings == null)
            {
                return HttpNotFound();
            }
            return View(roomBookings);
        }

        // POST: RoomBookings/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingId,CustomerName,CustomerNumber,CustomerEmail,CustomerAdress,BookingFrom,BookingTo,AssignRoomId,NoOfMembers,TotalAmount,PaymentTypeId,ServiceId,Comments,Confirmed")] RoomBookings roomBookings)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roomBookings).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roomBookings);
        }

        // GET: RoomBookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomBookings roomBookings = db.RoomBookings.Find(id);
            if (roomBookings == null)
            {
                return HttpNotFound();
            }
            return View(roomBookings);
        }

        // POST: RoomBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RoomBookings roomBookings = db.RoomBookings.Find(id);
            db.RoomBookings.Remove(roomBookings);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

HOTEL/Views/RoomBookings/Delete.cshtml
@model HOTEL.Models.RoomBookings

@{
    ViewBag.Title = "Бронирование";
}

<h2>Удаление</h2>

<h3>Вы действительно хотите удалить эту запись?</h3>
<div>
    <h4>Бронирование</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerAdress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerAdress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookingFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookingTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignRoomId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignRoomId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfMembers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfMembers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentTypeId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("< Назад к списку", "Index")
    </div>
    }
</div>

HOTEL/Views/RoomBookings/Edit.cshtml
@model HOTEL.Models.RoomBookings

@{
    ViewBag.Title = "Бронирование";
}

<h2>Бронирование</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.BookingId)

    <div class="form-group">
        @Html.LabelFor(model => model.Confirmed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Confirmed, new SelectList(ViewBag.ConfirmedList, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Confirmed, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerAdress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerAdress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerAdress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BookingFrom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BookingFrom, new { htmlAttributes = new { @class = "form-control", @Value = Model.BookingFrom.ToString("yyyy-MM-dd") } })
            @Html.ValidationMessageFor(model => model.BookingFrom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BookingTo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BookingTo, new { htmlAttributes = new { @class = "form-control", @Value = Model.BookingTo.ToString("yyyy-MM-dd") } })
            @Html.ValidationMessageFor(model => model.BookingTo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AssignRoomId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AssignRoomId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AssignRoomId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NoOfMembers, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NoOfMembers, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NoOfMembers, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control form-control-lg w-90", style = "height:200px" } })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TotalAmount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.TotalAmount, new { @class = "form-control", type = "number" })
            @Html.ValidationMessageFor(model => model.TotalAmount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PaymentTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PaymentTypeId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PaymentTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("< Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HOTEL/Views/RoomBookings/Index.cshtml
@model IEnumerable<HOTEL.Models.RoomBookings>


@if (User.IsInRole("Admin"))
{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
else
{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<header>
    <style>
        .input-group-prepend,
        .input-group-append {
            width: auto;
        }

        .input-group .form-control {
            width: auto;
        }

        .status-1 {
            background-color: lightgreen;
        }

        .status-2 {
            background-color: lightyellow;
        }

        .status-3 {
            background-color: lightblue;
        }

        .status-4 {
            background-color: lightcoral;
        }
        #bookings-table {
            width: 100%;
            overflow-x: auto;
            align-content: center;
            align-items: center;
            height: 700px;
            overflow-y: auto;
        }
    </style>
    
</header>
@if (User.IsInRole("Admin"))
{
    <br /><br />
    <div class="row">
        <div class="col-md-6">
            @using (Html.BeginForm("Index", "RoomBookings", FormMethod.Get))
            {
                <div class="input-group mb-3">
                    @Html.TextBox("bookingId", ViewBag.BookingId as string, new { @class = "form-control", @placeholder = "Номер бронирования" })
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">Найти</button>
                    </div>
                </div>
            }
        </div>
        <div class="col-md-6">
            @using (Html.BeginForm("Index", "RoomBookings", FormMethod.Get))
            {
                <div class="input-group mb-3">
                    @Html.TextBox("customerNumber", ViewBag.CustomerNumber as string, new { @class = "form-control", @placeholder = "Номер телефона" })
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">Найти</button>
                    </div>
                </div>
            }
        </div>
    </div>
}
<br /><br />
@if (!User.IsInRole("Admin"))
{
    <br /><br />

    <div class="container">
        <p>
            Для уточнения деталей вашего бронирования введите номер бронирования, либо ваш номер телефона.
        </p>
        <p>
            Так же, подробная информация была отправлена на электронную почту, которую вы указали при бронировании.
        </p>
    </div>

    <div class="row" style="margin-top:1%; padding-left:18%; padding-right:18%;">

        @using (Html.BeginForm("Index", "RoomBookings", FormMethod.Get))
        {
            <div class="col-md-3">
                @Html.TextBox("bookingId", ViewBag.BookingId as string, new { @class = "form-control", @placeholder = "Введите номер бронирования" })
            </div>
            <div class="col-md-2" style="margin:5px;">
                <button type="submit" class="btn btn-outline-secondary">Найти</button>
            </div>
        }
        @using (Html.BeginForm("Index", "RoomBookings", FormMethod.Get))
        {
            <div class="col-md-3">
                @Html.TextBox("customerNumber", ViewBag.CustomerNumber as string, new { @class = "form-control", @placeholder = "Введите номер телефона" })
            </div>
            <div class="col-md-2" style="margin:5px;">
                <button type="submit" class="btn btn-outline-secondary">Найти</button>
            </div>
        }

    </div>

}
<br /><br />
      <div id="bookings-table">
          <table class="table">
              <tr>
                  <th>
                          Номер бронирования
                  </th>
                  <th>
                      Статус
                  </th>
                  <th>
                      ФИО
                  </th>
                  <th>
                      Телефон
                  </th>
                  <th>
                      Почта
                  </th>
                  <th>
                      Адрес
                  </th>
                  <th>
                          Дата заезда
                  </th>

                  <th>
                          Дата выезда
                  </th>
                  <th>
                      Номер комнаты
                  </th>
                  <th>
                      Количество ночей
                  </th>
                  <th>
                      Пожелания
                  </th>
                  <th>
                      Гость 1
                  </th>
                  <th>
                      Гость 2
                  </th>
                  <th>
                      Гость 3
                  </th>
                  <th>
                      Доп. услуги
                  </th>
                  <th>
                      Итоговая стоимость
                  </th>
                  <th>
                      Оплата
                  </th>
                  <th></th>
              </tr>

              @foreach (var item in Model)
              {
                  <tr class="status-@item.Confirmed">
                      <td>
                          @Html.DisplayFor(modelItem => item.BookingId)
                      </td>
                      <td>
                          @if (item.Confirmed == 1)
                          {
                              @Html.Raw("Новое")
                          }
                          else if (item.Confirmed == 2)
                          {
                              @Html.Raw("Подтверждено")
                          }
                          else if (item.Confirmed == 3)
                          {
                              @Html.Raw("В работе")
                          }
                          else if (item.Confirmed == 4)
                          {
                              @Html.Raw("Завершено")
                          }
                          else if (item.Confirmed == 5)
                          {
                              @Html.Raw("Отменено")
                          }
                          else
                          {
                              @Html.Raw("Неизвестный статус")
                          }
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.CustomerName)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.CustomerNumber)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.CustomerEmail)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.CustomerAdress)
                      </td>
                      <td>

                          @{
                              string date_start = ((DateTime)item.BookingFrom).Date.ToString("d");
                          }
                          <text>@date_start</text>
                      </td>
                      <td>

                          @{
                              string date_end = ((DateTime)item.BookingTo).Date.ToString("d");
                          }
                          <text>@date_end</text>
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.AssignRoomId)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.NoOfMembers)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.Comments)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.CustomerName1)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.CustomerName2)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.CustomerName3)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.Services.Name)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.TotalAmount)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.PaymentType.PaymentType1)
                      </td>
                      @if (User.IsInRole("Admin"))
                      {
                          <td>
                              <div class="btn-group">
                                  <button type="button" onclick="location.href='@Url.Action("Edit", new { id = item.BookingId })'" class="btn btn-warning"><i class="fa fa-pencil"></i> Редактировать</button>
                                  <button type="button" onclick="location.href='@Url.Action("Delete", new { id = item.BookingId })'" class="btn btn-danger"><i class="fa fa-trash"></i> Удалить</button>
                              </div>
                          </td>
                      }
                  </tr>
              }

          </table>
      </div>