HOTEL/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HOTEL.Controllers
{
    public class MenusController : Controller
    {
        // GET: Menus
        public ActionResult Index()
        {
            return View("Index");
        }
    }
}

HOTEL/Views/Menus/Create.cshtml
@model HOTEL.Models.Menu

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Menus", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Menu</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    @*Загрузка фотографий*@
    <div class="form-group">
        @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload" value="Обзор..." />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HOTEL/Views/Menus/Delete.cshtml
@model HOTEL.Models.Menu

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HOTEL/Views/Menus/Details.cshtml
@model HOTEL.Models.Menu

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HOTEL/Views/Menus/Edit.cshtml
@model HOTEL.Models.Menu

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Menu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HOTEL/Views/Menus/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Filippov Hotel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <script src="https://kit.fontawesome.com/bacc822a81.js" crossorigin="anonymous"></script>
    <style>
        section.site-hero {
            padding-top: 100px; /* Высота стандартного верхнего меню Bootstrap */
        }

        h1.heading {
            color: goldenrod;
            font-family: "Playfair Display", times, serif;
            font-size: 3em;
        }

        .image-block {
            height: 400px;
            background-size: cover;
            background-position: center;
        }

        .row {
            margin: 0;
        }

        .col-md-6 {
            margin-top: 30px;
            padding: 30px 30px;
        }

            .col-md-6 img {
                width: 100%;
                max-height: 300px;
                margin-bottom: 20px;
            }

            .col-md-6 ul {
                margin-top: 20px;
            }

            .col-md-6 li {
                margin-bottom: 5px;
            }

            .col-md-6 strong {
                font-size: 20px;
                display: block;
                margin-bottom: 10px;
            }

            .col-md-6 p {
                margin-top: 20px;
            }

        .line-row {
            display: flex;
            align-items: center;
        }

        .line-text {
            flex: 1;
            text-align: center;
            font-weight: bold;
            color: goldenrod;
            font-size: 2em;
        }

        .line-row::before,
        .line-row::after {
            content: "";
            border-bottom: 1px solid black;
            flex: 1;
            margin: 0 10px;
        }
    </style>
</head>


   @using (Html.BeginForm())
    {

        <div class="row" style="padding-left:12%; padding-right:12%">
              <div class="col-md-12" style="margin-bottom:15px">
                  <div class="col-md-12">
                      <div>
                          <img class="img-fluid my-4" src="/Images/Menu/fon.jpg" alt="Image">
                      </div>
                      <br />
                      <div class="col-md-12">
                          <p>
                              Раздел "Меню" на нашем сайте представляет полный список блюд и напитков, которые можно заказать в нашем ресторане.
                              Мы предлагаем различные категории блюд, включая закуски, салаты, основные блюда и десерты.
                              В меню вы найдете разнообразные блюда, приготовленные из свежих и качественных ингредиентов, а также напитки, включая вино, пиво и коктейли.
                          </p>
                          <p>
                              Мы также учитываем потребности наших гостей и предлагаем блюда для различных диетических ограничений, таких как вегетарианская, безглютеновая и др.
                          </p>
                          <p>
                              На странице меню сайта вы найдете фотографии блюд, которые помогут вам сделать выбор.
                              Каждое блюдо сопровождается подробным описанием ингредиентов, способом приготовления и ценой.
                          </p>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                              <img class="img-fluid my-4" src="/Images/Menu/continent.jpg" alt="Image">
                          </div>
                          <div class="col-md-6">
                              <strong>Континентальный затрак:</strong>
                              <ul>
                                  <li>Континентальный завтрак - это тип завтрака, который обычно подается в отелях и гостиницах в Европе и Северной Америке. Он отличается от традиционного английского завтрака, который включает в себя яичницу, бекон, колбасу и тосты.</li>
                                  <li>Континентальный завтрак обычно состоит из свежих фруктов, соков, йогурта, хлеба, выпечки, джемов, меда, сыра и мясных деликатесов, таких как ветчина или прошутто. Кофе, чай и горячий шоколад также могут быть включены в завтрак.</li>
                                  <li>Особенностью континентального завтрака является его легкость и простота. Он обычно не включает в себя тяжелых блюд, таких как жареные яйца или бекон, и предлагает более здоровые и легкие опции для тех, кто хочет начать свой день с более легкой пищи.</li>
                                  <li>Континентальный завтрак является отличным выбором для тех, кто хочет быстро и легко позавтракать перед началом своего дня, и для тех, кто хочет попробовать различные европейские и североамериканские продукты.</li>
                              </ul>
                              <p>Обращаем ваше внимание, что на фото изображен вариант блюда и сервировки. Реальное блюдо может несколько отличаться от представленного на фото.</p>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                              <img class="img-fluid my-4" src="/Images/Menu/america.jpg" alt="Image">
                          </div>
                          <div class="col-md-6">
                              <strong>Американский завтрак:</strong>
                              <ul>
                                  <li>Американский завтрак - это традиционный завтрак, который часто подается в ресторанах и кафе в Северной Америке. Он отличается от континентального завтрака более обильным и сытным составом.</li>
                                  <li>Обычно американский завтрак включает яичницу, бекон, колбасу, жареные картофельные дольки или хэшбраунсы, тосты, блины или вафли, а также кофе, чай и фруктовые соки.</li>
                                  <li>Яичница может быть приготовлена в различных вариантах - от простой яичницы-глазуньи до яичницы с добавлением овощей, сыра и мяса. Бекон и колбаса обычно жарятся на сковороде до хрустящей корочки. Хэшбраунсы - это жареные картофельные дольки, которые могут быть приготовлены с добавлением лука и других овощей. Тосты, блины или вафли могут быть поданы с маслом и кленовым сиропом или же со сливочным сыром и фруктами.</li>
                                  <li>Американский завтрак обычно очень сытный и обильный, и может быть отличным выбором для тех, кто хочет начать свой день с плотного и питательного завтрака. Однако, он может быть не самым лучшим выбором для тех, кто предпочитает более легкую и здоровую пищу.</li>
                              </ul>
                              <p>Обращаем ваше внимание, что на фото изображен вариант блюда и сервировки. Реальное блюдо может несколько отличаться от представленного на фото.</p>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                              <img class="img-fluid my-4" src="/Images/Menu/english.jpg" alt="Image">
                          </div>
                          <div class="col-md-6">
                              <strong>Американский завтрак:</strong>
                              <ul>
                                  <li>Английский завтрак - это традиционный завтрак Великобритании, который обычно включает в себя несколько тяжелых и сытных блюд.</li>
                                  <li>Основными компонентами английского завтрака являются яичница, бекон, колбасы, консервированные бобы, жареные грибы и помидоры, тосты и чай. Некоторые версии английского завтрака также могут включать кровяную колбасу и черный пудинг.</li>
                                  <li>Яичница в английском завтраке обычно жарится на сковороде и может быть приготовлена как яичница-глазунья, яичница-бол, яичница-омлет или яичница-пашот. Бекон и колбасы, как правило, жарятся на сковороде до золотистой корочки. Консервированные бобы обычно подаются в томатном соусе, а жареные грибы и помидоры дают английскому завтраку свежий вкус.</li>
                                  <li>Тосты обычно подаются с маслом и джемом, а чай с молоком. Черный пудинг и кровяная колбаса - это традиционные компоненты английского завтрака, которые могут быть не для всех, так как они обычно приготавливаются из крови и мяса.</li>
                              </ul>
                              <p>Обращаем ваше внимание, что на фото изображен вариант блюда и сервировки. Реальное блюдо может несколько отличаться от представленного на фото.</p>
                          </div>
                      </div>
                  </div>
              </div>
            

        </div>
        <div class="row" style="padding-left:15%; padding-right:15%">
            <div class="line-row">
                <span class="line-text">Забронируйте сейчас</span>
            </div>
            <div class="col-md-4 with-icon">
                <h3>Гарантия низкой цены</h3>
                <p> <i class="bi bi-check2-circle" style="font-size:25px; color:goldenrod"></i> Гарантированно низкие цены при бронировании на официальном сайте Отеля «Filippov Hotel»</p>
            </div>
            <div class="col-md-4 with-icon">
                <h3>Бесплатная отмена бронирования</h3>
                <p>  <i class="bi bi-check2-circle" style="font-size:25px; color:goldenrod"></i> Вы не платите за отмену или изменения в бронировании при заказе через официальный сайт Отеля «Filippov Hotel»</p>
            </div>
            <div class="col-md-4 with-icon">
                <h3>Бесплатный Wi-Fi в номере</h3>
                <p>  <i class="bi bi-check2-circle" style="font-size:25px; color:goldenrod"></i> На всей территории Отеля «Filippov Hotel» действует бесплатный Wi-Fi</p>
            </div>
        </div>
    }